### PR TITLE
Requesting LICENSE change to BSD 3-Clause

### PR DESCRIPTION
**Pull request by kentrutan**
Thanks for making your excellent code and documentation available for speedy-antlr-tool! I'm evaluating it with the help of speedy-antlr-example for use in [Pymoca](https://github.com/pymoca/pymoca.git), a Python-based [Modelica](https://modelica.org/modelicalanguage.html) translator. I'm getting some compilation errors in `sa_*_translator.cpp` that I need to look into, but first...

Your GPL 3 license gives me pause. Pymoca uses BSD 3-Clause. The Pymoca team chose it (before my time) I think partly because ANTLR uses that license. I don't believe we want to encumber Pymoca with GPL 3 licensed code but speedy-antlr-tool I think would be fantastic for Pymoca assuming I can get it working. I will be quite happy to contribute back any fixes I might find, but I'm wondering if GPL 3 might be a show-stopper. I have not run it by the rest of the Pymoca team, but I personally don't think we want to change.

Would you consider changing to BSD 3-Clause? I believe it would be simpler for people to use given that is ANTLR's license and your tool is for use with ANTLR. I can also speak from experience that it may actually encourage more contributions to speedy-antlr-tool. I started work on Pymoca at my former company and it was much easier to get their approval to use and contribute my work back to Pymoca with its BSD 3-Clause license than it would have been with GPL.

### CODE REVIEW

**Comment by amykyta3** [comment]
Thank you for your interest in this project.
Could you clarify specifically what issues you have with the existing GPLv3 license? I understand that GPLv3 is on the more aggressive end of copyleft, but would be interested in specifics of how this affects you and the Pymoca project.

Please note that any code that is generated by speedy-antlr-tool is considered your own work (as it is essentially derived from your grammar) and you may license it in any way you wish. My intent was that the GPLv3 license is limited to the converter tool itself. I can clarify that in the docs if that helps.

**Comment by kentrutan** [comment]
That's great news! Your clarification helps a lot and would be great to have in the documentation. Even better would be to incorporate it into the header comments in the template files to make it totally clear what the license is for the generated code. It is not clear to me that the generated code is 100% my own work since it is a derivation of your template code. 

My main concerns with GPLv3 are related to my last comment above:
> I started work on Pymoca at my former company and it was much easier to get their approval to use and contribute my work back to Pymoca with its BSD 3-Clause license than it would have been with GPL.

I'm definitely not an open source license expert and haven't done any recent homework on it. What I remember from discussions with company experts was that if GPLv3 code touches your code, your entire code now has to be GPLv3. And that would be problematic for Pymoca since it is currently BSD-3-Clause and wants to remain that way. Your clarification makes that much less of an issue, but I was also thinking through the same pitfalls when taking snippets from your  speedy-antlr-example to apply to Pymoca's `setup.py`. I have absolutely no problem giving attribution and contributing improvements back, but having to change our license is not all that appealing.

I appreciate you being willing to discuss, no matter what you decide. I can see how asking for a licensing change could be seen as presumptuous. You have done great work here and am happy you took the time to put it out there as well as respond to this PR.

**Review by amykyta3 — APPROVED** [review]

**Comment by amykyta3** [comment]
Decided I'm ok with changing the licensing for this project outright.
Given the project's scope and intent, its not something that necessarily requires the GPLv3 license anyways.

**Comment by kentrutan** [comment]
Glad you agreed! I hope that maybe some day your code might be included in and maintained with the ANTLR Python runtime and this change will make it much more doable.

**Pull request merged**
